# Generated by Django 5.2.6 on 2025-09-08 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesubscription',
            name='course_slug',
        ),
        migrations.AddField(
            model_name='coursesubscription',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course'),
        ),
    ]
