# Generated by Django 5.2.6 on 2025-09-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_coursesubscription_course_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course'),
        ),
    ]
