# Generated by Django 5.2.6 on 2025-09-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_author_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline + Website Access')], default='online', max_length=10),
        ),
    ]
